### ISSUE TITLE
Appointment Booking

### ISSUE THREAD

**Issue by sosaidi** [sosaidi/AdvancedMD-frontend#13]
# User Story
As a user/ patient, I want to book an appointment with a doctor, so that I can receive timely medical care.

## Description
Allow patients to book new appointments by selecting a doctor, choosing a date and time, and submitting the request. Ensure the booking system is integrated with the doctor’s schedule.

## Tasks:
- [ ] Create an appointment booking form for patients.
- [ ] Allow patients to select available doctors and view their schedules.
- [ ] Implement appointment time selection based on doctor availability.
- [ ] Ensure that the booking is saved and reflected on the Doctor’s dashboard.
- [ ] Allow patient to select the kind of treatment (for example: yearly check-ups).
